### ISSUE TITLE
gltf -> filetype not allowed, glb -> missing contentid

### ISSUE THREAD

**Issue by rschrenk** [otacke/h5p-ar-scavenger#23]
I wanted to try this fabulous h5p library and uploaded this [free 3d model from sketchfab](https://sketchfab.com/3d-models/crystal-stone-rock-1ad829e2f464446fa4945562ab611255#download). It is available in the format gltf. When I wanted to upload this to my H5P activity it tells me, that this filetype was not allowed.

![filetype](https://user-images.githubusercontent.com/8080807/156766018-1e342fe0-fc62-4173-8e48-a2b584826ea9.png)

I then used blender to load the model and export it to glb-format. In this case H5P told me, that it was missing the contentid.

![contentid](https://user-images.githubusercontent.com/8080807/156766247-94a19d94-24a3-4a01-b54d-8d6985b4b339.png)

I also had the same errors with other 3d models that I tried. According to the Moodle administration of h5p libraries I used version `AR Scavenger (beta) (1.2.9)`

Although the used model is published under creative commons licence (cc-nc) I want to avoid uploading it persistently. Therefore, I created a wetransfer.com-Link, where the files that I used can be obtained for the next 7 days => [download](https://we.tl/t-zR6AESecZq)

**Comment by otacke** [comment]
This is documented in the [readme ](https://github.com/otacke/h5p-ar-scavenger#allow-gltf-and-glb-file-extensions)and not an issue with AR Scavenger, but with H5P core. The moodle plugin will need to get an update that allows glb and gltf files.

**Comment by otacke** [comment]
This is documented in the [readme ](https://github.com/otacke/h5p-ar-scavenger#allow-gltf-and-glb-file-extensions)and not an issue with AR Scavenger, but with H5P core. The moodle plugin will need to get an update that allows glb and gltf files.

**Comment by rschrenk** [comment]
ok, thank you

**Comment by rschrenk** [comment]
Hello,

I changed the allowed filetypes and the first error is gone. Unfortunately, it still complains about a missing contentid.

This applies to the beta version that I reported above, but also to the stable version that you recommend in the readme (https://www.olivertacke.de/labs/wp-content/uploads/2020/08/H5P.ARScavenger-library.h5p).

Kind regards

**Comment by otacke** [comment]
That's not an error message from H5P core, but actually seems to be passed by moodle, see https://github.com/moodle/moodle/blob/master/lang/en/error.php#L410. Unfortunately, that's beyond my powers.

And I can use the .glb file from your archive without any trouble by the way.

**Comment by otacke** [comment]
I have just checked on a local moodle instance (3.11) with both the H5P plugin for moodle and with moodle's custom integration - works like a charme, so I cannot even reproduce this issue.
