### ISSUE TITLE
Cannot add .gltf or .glb at all "file type isn't allowed"

### ISSUE THREAD

**Issue by Urpokarhu1** [otacke/h5p-ar-scavenger#24]
Hello,

I'm testing H5P AR Scavanger in Moodle 3.9 but when I try to upload f.ex. this gltf file;

https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/AnimatedCube/glTF/AnimatedCube.gltf

I get an error "file type isn't allowed" and .glb file isn't working either and gives the same error

![image](https://user-images.githubusercontent.com/53904029/159644475-c27da9c6-2547-4fea-8361-08c695e364cb.png)

**Comment by otacke** [comment]
Why not [look at the readme](https://github.com/otacke/h5p-ar-scavenger/blob/master/README.md) or [search the H5P forum for that issue](https://h5p.org/node/1253972)?

**Comment by Urpokarhu1** [comment]
Sorry about that, somehow i didn't consider readme to contain useful information :)
