### ISSUE TITLE
glb/gltf does not work in AR Scavenger.

### ISSUE THREAD

**Issue by AntDX316** [otacke/h5p-ar-scavenger#43]
glb/gltf does not work in AR Scavenger. It says the File Type doesn't work.

**Comment by otacke** [comment]
@AntDX316 As I already mentioned on the WordPress support forum (https://wordpress.org/support/topic/ar-scavenger-cannot-use-any-glb-gltf-it-says-file-type-isnt-allowed/#post-17146609): This is not an issue with the content type, but with the H5P plugin for WordPress. There's nothing that I can do here. I have no control over the code of the H5P plugin for WordPress, only H5P Group has.
